#!/usr/bin/env python3
"""Regenerate ATTRIBUTION.md from the data, so credits cannot drift.

    python3 tools/make_attribution.py

Every image credit and licence in the file comes straight from
web/content/locations.json, and the Qur'an editions from i18n/quran.json.
Edit those, not the Markdown.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "web" / "content"

LICENCE_LINKS = {
    "CC0": "https://creativecommons.org/publicdomain/zero/1.0/",
    "CC BY 2.0": "https://creativecommons.org/licenses/by/2.0/",
    "CC BY 3.0": "https://creativecommons.org/licenses/by/3.0/",
    "CC BY 4.0": "https://creativecommons.org/licenses/by/4.0/",
    "CC BY-SA 2.0": "https://creativecommons.org/licenses/by-sa/2.0/",
    "CC BY-SA 2.5": "https://creativecommons.org/licenses/by-sa/2.5/",
    "CC BY-SA 3.0": "https://creativecommons.org/licenses/by-sa/3.0/",
    "CC BY-SA 4.0": "https://creativecommons.org/licenses/by-sa/4.0/",
    "Public domain": "https://en.wikipedia.org/wiki/Public_domain",
}


def main() -> int:
    locations = json.loads((CONTENT / "locations.json").read_text(encoding="utf-8"))["locations"]
    editions = json.loads((ROOT / "i18n" / "quran.json").read_text(encoding="utf-8"))["editions"]

    with_image = sorted((l for l in locations if l["image"]), key=lambda l: l["name"]["en"])
    # A place with no image is either one we could not source faithfully, or a
    # route waypoint that was never a candidate. Say which, rather than implying
    # every gap is a failed search.
    unlocated = [l for l in locations if not l["image"] and l["precision"] in ("unlocated", "non-geographic")]
    no_image = [l for l in locations if not l["image"] and l["precision"] not in ("unlocated", "non-geographic")]

    rows = "\n".join(
        f"| {l['name']['en']} | [{l['image']['file']}]({l['image']['descriptionUrl']}) "
        f"| {l['image']['credit']} | {l['image']['license']} |"
        for l in with_image
    )
    used = sorted({l["image"]["license"] for l in with_image})
    links = " · ".join(f"[{lic}]({LICENCE_LINKS[lic]})" for lic in used if lic in LICENCE_LINKS)

    doc = f"""# Attribution

Third-party material redistributed by this project, with the credit each licence
requires. The interface displays every one of these in place; this file is the
complete list in one place.

Generated by `tools/make_attribution.py` from `web/content/locations.json` and
`i18n/quran.json` — regenerate it rather than editing it by hand.


## Qur'an translations

Qur'anic verses are never freshly translated for this project. Each quotation
reproduces a published edition, substituted at build time from `i18n/quran.json`:

| Language | Edition | Translator | Terms |
|---|---|---|---|
| English | {editions['en']['title']} ({editions['en'].get('year', '')}) | {editions['en']['translator']} | Public domain |
| German | {editions['de']['title']} | {editions['de']['translator']} | Free distribution; attribution required |

Six references are quoted: 96:1, 5:3, 19:56, 19:54, 21:85, and the phrase
*fath mubin* (48:1). The wordings were taken from the Quran.com API rather than
typed from memory. The Arabic text of the Qur'an is reproduced as it stands in
the source document.


## Location photographs — Wikimedia Commons

{len(with_image)} of the {len(locations)} registered places carry a photograph, each under a free
licence (CC0, CC BY, CC BY-SA or public domain). The fetch script refuses
anything else, and images were also reviewed by eye — an automated check alone
once returned a bird's nest for Badr and a football pitch for Ta'if.

Of the {len(locations) - len(with_image)} without one: {len(unlocated)} are route waypoints that cannot be located
or are not geographic places at all, so no photograph applies; the remaining
{len(no_image)} are places for which Commons held nothing that faithfully depicts them, and a
lookalike would misrepresent the place.

| Location | File | Author | Licence |
|---|---|---|---|
{rows}

Licence texts: {links}


## Maps

Map tiles and geographic data © [OpenStreetMap](https://www.openstreetmap.org/copyright)
contributors, under the Open Database Licence. Tiles are served from
OpenStreetMap's public tile servers.

Route waypoint coordinates were taken from OpenStreetMap and Wikidata where the
place survives as an identifiable modern settlement. Coordinates for historical
sites are curated approximations for map display, not citations — each carries a
`certainty` of established, traditional or disputed, and places that cannot be
fixed at all are marked `unlocated` and are never pinned.


## Mapping library

[Leaflet](https://leafletjs.com/) 1.9.4, © Vladimir Agafonkin and Leaflet
contributors, BSD-2-Clause. Vendored into `web/vendor/leaflet/` so the published
site has no runtime CDN dependency.
"""
    (ROOT / "ATTRIBUTION.md").write_text(doc, encoding="utf-8")
    print(f"ATTRIBUTION.md — {len(with_image)} images, {len(used)} distinct licences, "
          f"{len(unlocated)} waypoints/non-geographic, {len(no_image)} genuinely unsourced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
